[Feat] 메인 뷰 헤더 구현
DO-SOPT-CDS-TEAM-WEB7/Client pull request #13
Opened 2023-11-24 07:20 UTC by aazkgh

## 🔥 Related Issues

- close #6

## 💙 작업 내용
- [x] 로고 및 아이콘 삽입
- [x] font 및 컬러 지정
- [x] 반응형 설정 

## ✅ PR Point
- `position: absolute`로 박아서 반응형 설정되도록 했습니다! padding 값은 `calc` 사용해서 유동적으로 변화할 수 있도록 해주었습니다!
- 컴포넌트는 최대한 돌려쓰고 특별한 컬러를 가진 친구들은 class로 스타일 설정을 해주었습니다앙

2023-11-26 08:28 UTC, simeunseo requested changes
완젼 굳굳입니다!!! 고생했어용 ㅠㅠ 제가 리뷰남긴거 하나만 수정하고 알려주세요!!!

2023-11-26 08:28 UTC, simeunseo commented on src/components/main/Header.tsx
> +  padding: 3.4rem calc((100vw - 104.6rem) / 2) 0;
똑똑이!!!

2023-11-26 08:28 UTC, simeunseo commented on src/components/main/Header.tsx
> +  }
요거는 App.tsx의 Container에서 이미 해준 작업이기때문에, 여기서는 이 코드를 빼도 의도한대로 보여진답니다!!

2023-11-26 08:28 UTC, simeunseo commented on src/components/main/Header.tsx
> +  }
옹..! 깔끔하네요 사실 styled components의 주요 장점 중 하나가 className을 안써도 된다는 거여서 왠지 의미가 없어지는 느낌이 아닌가해서 저는 한번도 className을 써본적이 없거든요.. 그런데 이렇게 쓰니까 가독성, 유지보수성도 좋고 괜찮은 것 같아요...!!!

2023-11-26 16:16 UTC, se0jinYoon approved these changes
저는 반영할 수정사항 없슴니당 구웃!!!!!

2023-11-27 08:50 UTC, simeunseo approved these changes

2023-11-27 08:55 UTC, merged