[Feat] Footer 구현
DO-SOPT-CDS-TEAM-WEB7/Client pull request #20
Opened 2023-11-26 09:43 UTC by simeunseo

## 🔥 Related Issues

- close #5 

## 💙 작업 내용

- [x] 언어, 환율 변경 select box
- [x] 푸터 메뉴
- [x] 푸터 문구

## ✅ PR Point

- 그래도 그냥 네모로 박지 않고 select box와 option으로 구현했습니당 ㅎㅎ

## 😡 Trouble Shooting

- javascript에서는 기본 셀렉된 값 지정해놓을 때 option에 selected라는 속성을 넣어주면 됐었는데 react에서는 안되더라구요..! 그래서 이렇게 defaultValue라고 지정해주면 됩니다
  ```typescript
    <SelectBox className="exchange" defaultValue="KRW">
        <SelectBoxOption value="KRW">KRW</SelectBoxOption>
     </SelectBox>
```

2023-11-26 16:07 UTC, aazkgh approved these changes
딱히 수정사항 없는 거 같습니다 은서 바쁜데 짱짱❤

2023-11-26 16:07 UTC, aazkgh commented on src/components/common/Footer.tsx
> +          <SelectBox className="country">
은서 디테일 폼미폼미🔥

2023-11-26 16:38 UTC, se0jinYoon requested changes
구웃구웃 !! 저어기 간단한 리뷰 하나만 반영해주세용 !

2023-11-26 16:38 UTC, se0jinYoon commented on src/components/common/Footer.tsx
> +  console.log(ChevronDownIcon);
콘솔 필요없으니 지워줍시당 !

2023-11-27 08:26 UTC, simeunseo commented on src/components/common/Footer.tsx
> +  console.log(ChevronDownIcon);
어머이게뭐야~ 고마워요

2023-11-27 08:34 UTC, se0jinYoon approved these changes

2023-11-27 09:11 UTC, merged