[Feat] 여행지 추천 컴포넌트 구현
DO-SOPT-CDS-TEAM-WEB7/Client pull request #31
Opened 2023-11-27 18:08 UTC by aazkgh

## 🔥 Related Issues

- close #28

## 💙 작업 내용
- [x] 여행지 추천 공통 컴포넌트 구현

## ✅ PR Point

딱히 없습니다!

## 😡 Trouble Shooting
딱히 없습니다!

## 👀 스크린샷 / GIF / 링크
![image](https://github.com/DO-SOPT-CDS-TEAM-WEB7/Client/assets/101045330/4188ecfa-2b1d-4708-a86c-8838ce94ed0a)

2023-11-27 19:06 UTC, se0jinYoon requested changes
완~전 자잘한 거 하나 빼구 굿굿 !!!
타스 잘 쓰는구마잉 ~💗

2023-11-27 19:06 UTC, se0jinYoon commented on src/components/main/DesItem.tsx
> +}
아웅 타스 잘 쓰네!

2023-11-27 19:06 UTC, se0jinYoon commented on src/pages/Main.tsx
> +        <QnA />;
세미콜론 필요 없으면 지워줍시당 !

2023-11-27 23:47 UTC, simeunseo requested changes
와아 캐러셀 활용...❤️ 너무 고생했습니다!!! 타스도 잘 썼네에에에!!!! 역시 믿고있었다고...흑 
리뷰 하나만 확인해주고 노티주세요 👍👍👍

2023-11-27 23:47 UTC, simeunseo commented on src/components/main/DesCarousel.tsx
> +    </Carousel>
짱서진이 만든 캐러셀 척척 쓰는 짱가형..

2023-11-27 23:47 UTC, simeunseo commented on src/components/main/DesCarousel.tsx
> +    </Carousel>
key로 idx를 쓰는건 좋지 않아요! [index를 key로 쓰면 안되는 이유](https://medium.com/sjk5766/react-%EB%B0%B0%EC%97%B4%EC%9D%98-index%EB%A5%BC-key%EB%A1%9C-%EC%93%B0%EB%A9%B4-%EC%95%88%EB%90%98%EB%8A%94-%EC%9D%B4%EC%9C%A0-3ce48b3a18fb)
 `key={String(idx)+item.desName}` 정도로 idx와 이름을 조합해 unique한 key를 만들어서 써보면 어떨까 싶어요!
 아니면 어차피 여기는 서버에서 데이터 받아오는 곳 아니니까, 가형이가 만든 더미데이터 객체에 id 값을 직접 만들어서 사용하는 것도 좋은 방법이에요!!
```typescript
const DES_ITEM_DATA: DesItemProps[] = [
  {
    id:1,
    desName: '일본',
    desImg: JapanImg,
  },
...
```
요로코롬~~

2023-11-27 23:49 UTC, simeunseo commented on src/components/main/DesCarousel.tsx
> +    </Carousel>
근데 요거 서진언니 리뷰할 땐 못봤네ㅠㅠㅠ @se0jinYoon 언니도 캐러셀부분 이런식으로 바꿔주면 좋을거같아!!!!

2023-11-28 02:52 UTC, se0jinYoon commented on src/components/main/DesCarousel.tsx
> +    </Carousel>
옴마마 ! 이거 어디서 들어보긴 했었는데 약간 흐린눈 닫힌귀로 살았었는데 드디어 제대로 된 이유를 알았따 ... 흐흐 수정해두겠슴당 ~~

2023-11-29 20:11 UTC, se0jinYoon approved these changes

2023-11-29 20:16 UTC, simeunseo approved these changes

2023-11-29 22:32 UTC, merged