[Feat] 비행기 추천 컴포넌트 구현
DO-SOPT-CDS-TEAM-WEB7/Client pull request #33
Opened 2023-11-27 19:31 UTC by aazkgh

## 🔥 Related Issues

- close #32 

## 💙 작업 내용

- [x] 추천 항공편을 공통 컴포넌트 캐러셀을 이용해 구현
- [x] 타이틀 및 헤더 붙이기
- [x] 필터링 버튼 추가  

## ✅ PR Point

딱히 없습니당

## 😡 Trouble Shooting

딱히 없습니당

## 👀 스크린샷 / GIF / 링크

![image](https://github.com/DO-SOPT-CDS-TEAM-WEB7/Client/assets/101045330/2f9ada83-7826-450c-9820-4afe18bcdff0)
메인 페이지의 콘테이너 컴포넌트는 마지막에 구현할 예정이라 위아래에 있는 컴포넌트들과의 gap같은 거는 보지 말구 딱 비행기 추천 컴포넌트만 봐주세요!

2023-11-27 23:53 UTC, simeunseo requested changes
고생 많았어요! 아고 이번 새벽에 엄청 많은 것들을 해냈네 ㅠㅠㅠ 하 쿨쿨자버린 나를 반성하며.. 너무 열심히해주는 가형이 서진언니 보고 다시 달려보겠씁니다 화이팅!!!!

2023-11-27 23:53 UTC, simeunseo commented on src/components/main/FlightCarousel.tsx
> +// eslint-disable-next-line import/order
흠냐 이거 청기백기 import sort 문제 해결방법을 좀 알아봐야겠네요ㅠㅠㅠㅠ 대체 왜이러는것이냐!!!

2023-11-27 23:53 UTC, simeunseo commented on src/components/main/FlightCarousel.tsx
> +      ))}
요기도 똑같이 key값 지정 수정해주어요...❤️

2023-11-27 23:53 UTC, simeunseo commented on src/components/main/FlightItem.tsx
> +}
흑흑 짜란다~~ export해서 다른데서도 써주는거 완전 굳굳굳뜨

2023-11-28 02:55 UTC, se0jinYoon commented on src/components/main/FlightCarousel.tsx
> +// eslint-disable-next-line import/order
청기백기 ㅋㅋㅋㅋㅋ ㅠㅠ

2023-11-28 02:57 UTC, se0jinYoon approved these changes
구웃 반영할 수정사항 없숨당 ! 캐러셀 잘 써주어서 너무 기쁠 뿐 ..

2023-11-29 20:15 UTC, simeunseo approved these changes

2023-11-29 21:43 UTC, merged