[Feat] 공통 캐러셀
DO-SOPT-CDS-TEAM-WEB7/Client pull request #9
Opened 2023-11-23 09:19 UTC by se0jinYoon

## 🔥 Related Issues

- close #4 

## 💙 작업 내용

- [x] 캐러셀 라이브러리 설치
- [x] 캐러셀 라이브러리 커스텀

## ✅ PR Point

### 1. 라이브러리 도입기 
처음에는 `Swiper ` 사용하려고 했는데 버전 이슈로 문제를 겪어서 ` React-slick`을 사용하게 되었습니다.
<img width="638" alt="스크린샷 2023-11-22 오후 5 03 16" src="https://github.com/DO-SOPT-CDS-TEAM-WEB7/Client/assets/109661444/abe6757c-3077-4d96-bc2d-17260f6603c9">

모든 걸 설치하고 import해줘도 import 에러 발생하는 `swiper `...

<img width="950" alt="스크린샷 2023-11-22 오후 5 11 24" src="https://github.com/DO-SOPT-CDS-TEAM-WEB7/Client/assets/109661444/e7c7ffb9-0cda-4d6c-a34a-4d9b8cea37e4">
그리고 리액트와 같이 쓰일 수 있는 부분들도 버전이 업데이트 되면서 없어짐 ..

### 2. 사용법

[✅ 구현영상과 관련된 커밋기록](https://github.com/DO-SOPT-CDS-TEAM-WEB7/Client/commit/cb3600dc8abb8c792b2b0925977815cfa997d6fc)

### 1️⃣ 캐러셀에 넣고 싶은 item들을 컴포넌트로 만들기
<img width="224" alt="스크린샷 2023-11-23 오후 6 15 05" src="https://github.com/DO-SOPT-CDS-TEAM-WEB7/Client/assets/109661444/ac9e4c3e-94cd-459e-a066-b1959aed01fb">

### 2️⃣ Carousel의 children 넣으려는 item map 넘겨주기
```typescript
// TickeList > TicketListCarousel.tsx
...
  <Carousel dataLength={DUMMY.length}>
    {DUMMY.map((item, idx) => (
      <TicketListCarousel key={idx} hotelName={item.hotelName} hotelRoom={item.hotelRoom} hotelBed={item.hotelBed} />
    ))}
  </Carousel>
...
```
🚨 Carousel의 prop으로 **`item의 개수`를 넘겨주어야 함**
```
 <Carousel dataLength={DUMMY.length}>
```

### 3️⃣ 렌더링하려는 곳에 Carousel 위치시키기
```
import { BrowserRouter, Route, Routes } from 'react-router-dom';

import Main from '../../pages/Main';
import TicketListTest from '../ticketList/TicketListTest';
const Router = () => {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/" element={<Main />} />
        <Route path="/test" element={<TicketListTest />} />
      </Routes>
    </BrowserRouter>
  );
};
export default Router;
```

## 😡 Trouble Shooting
### 1. 캐러셀 아이템 간 여백 주기
-  `gap` : 캐러셀의 부모 컴포넌트를 `flex`로 감싸게 되는 순간 .. 캐러셀의 넓이와 높이가 어마무시하게 커져버리는 이슈가 발생해서 사용 불가능
- 캐러셀 아이템에 `margin-right` 주기
가장 왼쪽과 가장 오른쪽의 아이템은 양끝에 딱 붙어서 배치되어야 하는데 오른쪽 margin이 생겨서 가장 오른쪽 아이템에 여백이 생기는 문제 발생
<img width="1455" alt="스크린샷 2023-11-23 오전 6 42 50" src="https://github.com/DO-SOPT-CDS-TEAM-WEB7/Client/assets/109661444/9f7bbb82-7aae-40d0-b2f9-258bec78c7f3">

### ➡️ 해결 
**캐러셀을 감싸는 부모 컴포넌트**에 설정하고 싶은 아이템간 여백만큼 **음수값**으로 margin-right 주기
**캐러셀 아이템 자체**에는 설정하고 싶은 아이템간 여백만큼 **양수값**으로 padding-right 주기
이렇게 하면 상쇄되어 아이템 간 간격 지정 가능 !
```typescript
  .slick-slide > div {
    padding-right: 1.6rem;
  }

  .slick-list {
    margin-right: -1.6rem;
  }
```

### 2. 변수명 eslint key-value-type 에러
**state명** `currentSlide`과 **마지막 캐러셀 아이템을 위한 index명** `disappearIndex`을 `camelCase`로 지정
style에 prop으로 넘겨서 **key-value**의 **value값**으로 해당 변수들을 사용하게 됨
```typescript
nextArrow: <NextArrow currentslide={currentslide} disappearindex={disappearindex} />
...
const NextArrow = (props: ArrowProps) => {
  const { disappearindex, className, currentslide, style, onClick } = props;
  return (
    <NextBtn
      className={className}
      style={{ ...style, display: 'flex', visibility: currentslide === disappearindex ? 'hidden' : 'visible' }}
      onClick={onClick}>
      <ArrowImg src={ForwardArrow} alt="다음으로" />
    </NextBtn>
  );
};
```
<img width="568" alt="스크린샷 2023-11-23 오후 6 09 52" src="https://github.com/DO-SOPT-CDS-TEAM-WEB7/Client/assets/109661444/5d9d3176-9bc4-4f3e-91e5-307c8caf4690">

`key-value-type 에러` (value값에는 camelCase 사용 불가능) 발생해서 **자동저장 시 `value값`이 자동으로 `lowercase`로 변환되어 찾을 수 없는 값이 되어 렌더링 에러 발생**

### ➡️ 해결 
state명,  캐러셀 아이템을 위한 index명 모두 lowercase로 지정
```typescript
const [currentslide, setCurrentSlide] = useState(0);
const disappearindex: number = dataLength - 4;
```

### 3. 피그마 이미지 추출 시 알 수 없는 배경
### ➡️ 해결 
솔로몬 은서가 그림자라고 알려주어서 그림자 빼고 추출 후 css로 그림자 설정

### 4. 초기 세팅 body: flex에 따른 문제
위에서 언급한 것 처럼 캐러셀의 부모 컴포넌트를 `flex`로 감싸게 되는 순간 .. **캐러셀의 넓이와 높이가 어마무시하게 커져버리는 이슈가 발생**하기 때문에 **캐러셀 컴포넌트**에서는 `body: flex`를 **해제**해야 하는 문제 발생

### ➡️ 해결 
솔로몬 은서가 body를 불러와서 스타일 지정하라고 알려주어서 !! 해결 완료
```typescript
  useEffect(() => {
    const originalDisplayStyle = document.body.style.display;
    document.body.style.display = 'block';

    return () => {
      document.body.style.display = originalDisplayStyle;
    };
  }, []);
```

### 5. 처음과 끝에서 양쪽 화살표 없애기
준비물
- 현재 아이템의 인덱스를 저장하는 `state`,
```typescript
  const [currentslide, setCurrentSlide] = useState(0);
```
- 라이브러리에서 제공하는 `이전으로`, `다음으로` 버튼과 관련된 동작을 지정할 수 있는 **메소드**
``` typescript
    afterChange: (index: number) => setCurrentSlide(index),
    beforeChange: (current: number, next: number) => setCurrentSlide(next),
```

`afterChange` : 슬라이더가 변경된 **후** 호출됨, state를 변경된 아이템의 index로 지정
`beforeChange`: 슬라이더가 변경되기 **전**에 호출됨, current는 현재 아이템, next는 다음 아이템을 저장함
이때 모든 값은 슬라이더의 **가장 앞에 있는 아이템을 기준**으로 설정되므로, 마지막 아이템인지 알려면 
전체 데이터.`length - 1 - 3`
>-1 : 길이를 인덱스로 변환 (0부터 시작하니깐)
-3 : 캐러셀에 4개의 아이템이 있으므로 현재 아이템 (캐러셀의 가장 왼쪽 아이템)을 제외한 아이템 개수 3개 빼기

이렇게 `변경된 state`가 prop으로 받아온 `마지막 아이템 index - 4` 과 **같을 경우 다음으로 화살표 없애기**
```typescript
    <NextBtn
        ...
      style={{ ...style, display: 'flex', visibility: currentslide === disappearindex ? 'hidden' : 'visible' }}
      /NextBtn>

```

## 👀 스크린샷 / GIF / 링크

https://github.com/DO-SOPT-CDS-TEAM-WEB7/Client/assets/109661444/5e544641-74c6-44a3-94ba-6f5eba34ce51

## 📚 Reference

[React-slick 공식문서](https://react-slick.neostack.com/)
[라이브러리 커스텀 예시 벨로그](https://velog.io/@juno7803/3%EB%B6%84-TIPS-React-Slick-%EC%89%BD%EA%B2%8C-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0)

2023-11-25 06:41 UTC, simeunseo reviewed
와 진짜 쉽지 않았을텐데 뚝-딱 해낸... 많은 트러블 슈팅이 있었겠죠 너무 고생했슴니당 ..ㅠㅠㅠㅠ 어려운거 하나 끝냈으니 쑥쑥 해봅시다 ㅎㅎㅎ 그 아까 따로 말했던 오른쪽 슬라이드 넘길 때 튀어나오는 영역 관련 문제는 나중에 시간 남으면 해보도록 해유,, 짱짱!!!! 리뷰 남겨놓은거만 바꾸고 노티주세용ㅎㅎ

2023-11-25 06:41 UTC, simeunseo commented on src/components/common/Carousel.tsx
> +    infinite: true,
이거 infinite: false로 만드는 게 맞는 것 같아요!! 그 마지막 넘기기에서도 마우스로 드래그하면 다시 처음으로 돌아가지더라구요

2023-11-26 16:03 UTC, se0jinYoon commented on src/components/ticketList/TicketListCarousel.tsx
> +const TicketListCarousel = (props: TicketListCarouselProps) => {
테스트한다고 변수명 막 지었네요 ㅠㅠㅠ 피드백 반영해두었습니당 !

2023-11-26 16:03 UTC, se0jinYoon commented on src/components/common/Carousel.tsx
> +    infinite: true,
반영 완 !

2023-11-26 17:55 UTC, aazkgh requested changes
언니 너무 힘들었겠다ㅜ 캐러셀 라이브러리 구현하느라 고생했어요옹 특히, 정성스런 PR이랑 트러블슈팅까지,,,,ㅜ 혹시 이거 쇽샥해가지고 내가 노션에 옮겨두 될까?? 그리고 오늘 솝커톤도 완전 수고했어❤❤❤❤❤❤❤❤❤❤ 응애와비리드,,,,최우수상과 인기상 2관왕,,,,폼미폼미 ><

2023-11-26 17:55 UTC, aazkgh commented on src/components/common/Router.tsx
> +        <Route path="/ticketList" element={<HotelItem />} />
요거 컴포넌트 나중에 hotelitem 아니라 페이지로 이동하게 바꿔주는 거 맞을까요오~??

2023-11-26 18:00 UTC, se0jinYoon commented on src/components/common/Router.tsx
> +        <Route path="/ticketList" element={<HotelItem />} />
허억 맞아유 ! 테스트한다고 저렇게 남겨뒀네 !! 쇽샥 삭제하러 가보겟숨다

2023-11-26 18:03 UTC, se0jinYoon commented on src/components/common/Router.tsx
> +        <Route path="/ticketList" element={<HotelItem />} />
아 그리구 쇽샥 트러블 슈팅 옮기기 너무너무 굿굿ㄱ숫굿굿굿

2023-11-26 18:04 UTC, aazkgh approved these changes

2023-11-26 18:05 UTC, merged